/*********************
 * Creates testFns.lookupsHttpResponse
 * a subset of the server's HTTP response to a 'lookups' request.
 *
 * Generated by hand per the following procedure (total time: 15 minutes)
 * - Send 'lookups' request in Chrome Postman extension
 * - paste headers here
 * - paste response here
 * - reduce it heavily by deleting most data
 * - deliberately eliminate spice options to see what happens
 */
(function(testFns){
    var headers = {
        "Cache-Control": "no-cache, private, no-store, must-revalidate, max-stale=0, post-check=0, pre-check=0",
        "Connection": "keep-alive",
        "Content-Encoding": "gzip",
        "Content-Type": ": application/json, text/html; charset=utf-8",
        "Date": "Thu, 10 Apr 2014 18:42:08 GMT",
        "Transfer-Encoding": "chunked",
        "Vary": "Accept-Encoding",
        "X-Powered-By": "Express",
        "etag": "675943714"
    };
    var data =    {
        "OrderStatus": [
            {
                "_id": 1,
                "name": "Ordered",
                "$type": "OrderStatus"
            },
            {
                "_id": 2,
                "name": "PickedUp",
                "$type": "OrderStatus"
            },
            {
                "_id": 3,
                "name": "Delivered",
                "$type": "OrderStatus"
            },
            {
                "_id": 4,
                "name": "Cancelled",
                "$type": "OrderStatus"
            },
            {
                "_id": 5,
                "name": "Pending",
                "$type": "OrderStatus"
            }
        ],
        "Product": [
            {
                "_id": 1,
                "type": "pizza",
                "name": "Plain Cheese",
                "description": "Your basic plain cheese pizza with no toppings.\nIncludes tomato sauce, mozzarella, oregano and a sprinkling of cheddar",
                "image": "plaincheese.jpg",
                "hasOptions": false,
                "isPremium": false,
                "isVegetarian": true,
                "withTomatoSauce": true,
                "sizeIds": null,
                "$type": "Product"
            },
            {
                "_id": 2,
                "type": "pizza",
                "name": "Make Your Own",
                "description": "Make your own\nIncludes tomato sauce, mozzarella, oregano and a sprinkling of cheddar",
                "image": "makeyourown.jpg",
                "hasOptions": true,
                "isPremium": false,
                "isVegetarian": true,
                "withTomatoSauce": true,
                "sizeIds": null,
                "$type": "Product"
            },
            {
                "_id": 23,
                "type": "salad",
                "name": "Chicken Caesar Salad",
                "description": "Traditional Caesar with your choice of grilled or BBQ chicken",
                "image": "chickencaesarsalad.jpg",
                "hasOptions": true,
                "isPremium": false,
                "isVegetarian": false,
                "withTomatoSauce": false,
                "sizeIds": [
                    9
                ],
                "$type": "Product"
            },
            {
                "_id": 31,
                "type": "drink",
                "name": "Cola",
                "description": "Cola",
                "image": "cola.jpg",
                "hasOptions": false,
                "isPremium": false,
                "isVegetarian": false,
                "withTomatoSauce": false,
                "sizeIds": [
                    10,
                    11
                ],
                "$type": "Product"
            },
            {
                "_id": 36,
                "type": "drink",
                "name": "Lemon Spruce",
                "description": "Lemon Spruce",
                "image": "lemonspruce.jpg",
                "hasOptions": false,
                "isPremium": false,
                "isVegetarian": false,
                "withTomatoSauce": false,
                "sizeIds": [
                    10
                ],
                "$type": "Product"
            }
        ],
        "ProductOption": [
            {
                "_id": 1,
                "type": "crust",
                "name": "Classic Crust",
                "factor": 0,
                "productTypes": [
                    "pizza"
                ],
                "$type": "ProductOption"
            },
            {
                "_id": 4,
                "type": "sauce",
                "name": "Tomato",
                "factor": 0,
                "productTypes": [
                    "pizza"
                ],
                "$type": "ProductOption"
            },
            {
                "_id": 5,
                "type": "sauce",
                "name": "Pesto*",
                "factor": 2,
                "productTypes": [
                    "pizza"
                ],
                "$type": "ProductOption"
            },
            {
                "_id": 6,
                "type": "sauce",
                "name": "Salsa",
                "factor": 1,
                "productTypes": [
                    "pizza"
                ],
                "$type": "ProductOption"
            },
            {
                "_id": 14,
                "type": "cheese",
                "name": "Fontina & Swiss",
                "factor": 1,
                "productTypes": [
                    "pizza",
                    "salad"
                ],
                "$type": "ProductOption"
            },
            {
                "_id": 20,
                "type": "veggie",
                "name": "Black Olives",
                "factor": 1,
                "productTypes": [
                    "pizza",
                    "salad"
                ],
                "$type": "ProductOption"
            },
            {
                "_id": 21,
                "type": "veggie",
                "name": "Broccoli",
                "factor": 1,
                "productTypes": [
                    "pizza",
                    "salad"
                ],
                "$type": "ProductOption"
            },
            {
                "_id": 42,
                "type": "meat",
                "name": "Italian Sausage",
                "factor": 1,
                "productTypes": [
                    "pizza",
                    "salad"
                ],
                "$type": "ProductOption"
            },
            {
                "_id": 46,
                "type": "meat",
                "name": "BBQ Chicken*",
                "factor": 2,
                "productTypes": [
                    "pizza",
                    "salad"
                ],
                "$type": "ProductOption"
            },
            {
                "_id": 47,
                "type": "meat",
                "name": "Thai Chicken*",
                "factor": 2,
                "productTypes": [
                    "pizza",
                    "salad"
                ],
                "$type": "ProductOption"
            },
            {
                "_id": 48,
                "type": "meat",
                "name": "Grilled Chicken*",
                "factor": 2,
                "productTypes": [
                    "pizza",
                    "salad"
                ],
                "$type": "ProductOption"
            },
            {
                "_id": 58,
                "type": "saladDressing",
                "name": "No Dressing",
                "factor": 0,
                "productTypes": [
                    "salad"
                ],
                "$type": "ProductOption"
            },
            {
                "_id": 59,
                "type": "saladDressing",
                "name": "Vinaigrette",
                "factor": 1,
                "productTypes": [
                    "salad"
                ],
                "$type": "ProductOption"
            }
        ],
        "ProductSize": [
            {
                "_id": 1,
                "type": "pizza",
                "name": "Personal 8\"",
                "price": 6.15,
                "premiumPrice": 7.65,
                "toppingPrice": 0.65,
                "isGlutenFree": false,
                "$type": "ProductSize"
            },
            {
                "_id": 2,
                "type": "pizza",
                "name": "Medium 12\"",
                "price": 12.4,
                "premiumPrice": 16.95,
                "toppingPrice": 1.35,
                "isGlutenFree": false,
                "$type": "ProductSize"
            },
            {
                "_id": 3,
                "type": "pizza",
                "name": "Large 14\"",
                "price": 14.45,
                "premiumPrice": 20.95,
                "toppingPrice": 1.7,
                "isGlutenFree": false,
                "$type": "ProductSize"
            },
            {
                "_id": 7,
                "type": "salad",
                "name": "Side",
                "price": 3.95,
                "premiumPrice": null,
                "toppingPrice": 0.65,
                "isGlutenFree": false,
                "$type": "ProductSize"
            },
            {
                "_id": 8,
                "type": "salad",
                "name": "Entree",
                "price": 7.95,
                "premiumPrice": null,
                "toppingPrice": 1.3,
                "isGlutenFree": false,
                "$type": "ProductSize"
            },
            {
                "_id": 9,
                "type": "salad",
                "name": "Entree",
                "price": 8.95,
                "premiumPrice": null,
                "toppingPrice": 1.3,
                "isGlutenFree": false,
                "$type": "ProductSize"
            },
            {
                "_id": 10,
                "type": "drink",
                "name": "Can",
                "price": 1.5,
                "premiumPrice": null,
                "toppingPrice": null,
                "isGlutenFree": false,
                "$type": "ProductSize"
            },
            {
                "_id": 11,
                "type": "drink",
                "name": "20 oz",
                "price": 1.95,
                "premiumPrice": null,
                "toppingPrice": null,
                "isGlutenFree": false,
                "$type": "ProductSize"
            }
        ]
    };

    testFns.lookupsHttpResponse = {
        headers: headers,
        data: data
    };

})(window.testFns);
