/*
 * Sets up the model with client-side metadata 
 * and any other model extensions we need (none so far)
 */
(function (){
    'use strict';
    angular.module('app').factory('model', ['breeze', service]);

    function service(breeze){
        var model =  {
            setModel: setModel
        };
        return model;
        //////////////////////

        function setModel(manager) {
            var store = manager.metadataStore;
            var helper = new breeze.config.MetadataHelper('Model', breeze.AutoGeneratedKeyType.Identity);
            var DT = breeze.DataType;

            // Associate the metadata with the manager's data service
            store.addDataService(manager.dataService);

            addTodoItemType();

            function addTodoItemType() {
                var entityType = {
                    name: "TodoItem",
                    defaultResourceName: "TodoItem",
                    dataProperties: {
                        id:       { type: DT.Guid },
                        text:     { max: 50, required: true  },
                        complete: { type: DT.Boolean, required: true }
                    }
                };

                helper.addTypeToStore(store, entityType);

                return entityType;
            }
        }
    }
})();
